# Generated by Django 4.2.4 on 2023-09-17 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='content',
        ),
    ]
