# Generated by Django 4.2.4 on 2023-08-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('due_date', models.DateTimeField()),
                ('overdue', models.BooleanField(default=False)),
                ('tasks_owners', models.JSONField(blank=True, default=list)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('state', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
    ]
